ft-generator - fix build fail due to ignored non-null attribute
On newer systems, std::fclose has a __attribute__((nonnull(1))) defined
which makes it unable to be directly used in std::unique_ptr.

/flowtest/tools/ft-generator/src/pcapwriter.cpp: In constructor
‘generator::PcapWriter::PcapWriter(const std::string&)’:
/flowtest/tools/ft-generator/src/pcapwriter.cpp:25:58: error: ignoring
attributes on template argument ‘int (*)(FILE*)’
[-Werror=ignored-attributes]
   25 |         std::unique_ptr<std::FILE, decltype(&std::fclose)> fp(